#!/usr/bin/env python3
"""Generate test/golden.h from the Mac light language.

The C table in r2_lights.c is a hand port of mac-prototype/r2_lights.py.
This writes what the PYTHON says every state shows, sampled on a grid, so the
host test can compare the port against the source instead of against itself.

Re-run after any change to either table:

    python3 firmware/platform/r2_lights/tools/gen_golden.py

test/run_tests.sh regenerates it to a scratch file and fails on any diff, so
a change to r2_lights.py cannot leave a stale golden passing.

NOT COVERED: the grid stops at 7 s, before `listen`'s one-shot breath settles
(13.2 s) and just short of `thinking`'s (7.2 s). Both hold their last member
by the same code path the 7 s grid does exercise.

The grid is every 25 ms to 7 s. Every period in the table is a multiple of
25 ms (0.25, 0.45, 0.9, 1.0, 1.2, 2.2, 2.4, 3.0 s, and their halves), so it
lands ON every transition as well as between them -- the instants where a
port that rounds or truncates differently would disagree.
"""
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
sys.path.insert(0, str(ROOT / "mac-prototype"))

import r2_lights as LG  # noqa: E402

GRID_MS = range(0, 7001, 25)
VALUES = (1.0, 0.25)
# The C enum's order. A mismatch is refused, not silently re-mapped.
ORDER = ("idle", "wake", "listen", "thinking", "attention", "danger",
         "misheard", "offline", "waiting", "sleep")


def frame(state, t, value):
    """All eight channels at t, zeros for unused fixtures -- the shape
    `LG.assertion` writes, at any t rather than only frame zero."""
    if not state.dimmable:
        value = 1.0
    ch = [0] * 8
    for bits, pat in ((LG.FRONT_BITS, state.front), (LG.BACK_BITS, state.back)):
        for b, v in LG._psi_channels(bits, pat, t, value).items():
            ch[int(b)] = v
    if state.holo is not None:
        for b, v in LG._level_channels(LG.LED_HOLO, state.holo, t, value).items():
            ch[int(b)] = v
    if state.logic is not None:
        for b, v in LG._level_channels(LG.LED_LOGIC, state.logic, t, value).items():
            ch[int(b)] = v
    return ch


def main():
    if tuple(LG.STATES) != ORDER:
        sys.exit(f"r2_lights.py rows are {tuple(LG.STATES)}; the C enum "
                 f"expects {ORDER}. Update both, then re-run.")
    out = [
        "/* GENERATED by tools/gen_golden.py from mac-prototype/r2_lights.py.",
        " * Do not edit; re-run the generator. */",
        "#define GOLDEN_STATES %d" % len(ORDER),
        "#define GOLDEN_VALUES %d" % len(VALUES),
        "#define GOLDEN_SAMPLES %d" % len(GRID_MS),
        "#define GOLDEN_STEP_MS %d" % GRID_MS.step,
        "static const double GOLDEN_VALUE[GOLDEN_VALUES] = {%s};"
        % ", ".join(repr(v) for v in VALUES),
        "static const char *const GOLDEN_NAME[GOLDEN_STATES] = {%s};"
        % ", ".join('"%s"' % n for n in ORDER),
        "static const unsigned char GOLDEN[GOLDEN_STATES][GOLDEN_VALUES]"
        "[GOLDEN_SAMPLES][8] = {",
    ]
    for name in ORDER:
        st = LG.STATES[name]
        out.append(" { /* %s */" % name)
        for value in VALUES:
            rows = ["{%s}" % ",".join(str(c) for c in frame(st, ms / 1000, value))
                    for ms in GRID_MS]
            out.append("  {" + ",".join(rows) + "},")
        out.append(" },")
    out.append("};")
    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parent / "test" / "golden.h"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest}: {len(ORDER)} states x "
          f"{len(VALUES)} values x {len(GRID_MS)} samples")


if __name__ == "__main__":
    main()
