#!/usr/bin/env python3
"""Generate C test vectors from the validated Python packet layer.

#114 AC1 requires the C encoder to be byte-identical to mac-prototype/r2_probe.py,
whose packet layer was cross-checked three ways (spherov2, the claude-r2d2-buddy
C firmware, and a clean-room trace). So the fixtures are GENERATED from it rather
than hand-written: a hand-written vector only encodes what the author already
believed.

    python3 gen_fixtures.py > fixtures.h
"""
import importlib.util
import sys
from pathlib import Path

def _find_reference():
    """Walk up for mac-prototype/r2_probe.py rather than counting parents --
    a hardcoded depth breaks silently the first time this file moves."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        cand = parent / "mac-prototype" / "r2_probe.py"
        if cand.is_file():
            return cand
    raise SystemExit("cannot find mac-prototype/r2_probe.py above " + str(here))


REF = _find_reference()


def load_reference():
    spec = importlib.util.spec_from_file_location("rp", REF)
    m = importlib.util.module_from_spec(spec)
    sys.modules["rp"] = m          # @dataclass needs the module registered
    try:
        spec.loader.exec_module(m)
    except SystemExit:
        pass
    return m


def c_bytes(b):
    return "{" + ", ".join(f"0x{x:02X}" for x in b) + "}" if b else "{0}"


def main():
    rp = load_reference()
    DID, CID = 0x13, 0x0D          # power / wake, the command we have sent most

    cases = [
        ("wake_seq2",        DID, CID, 0x02, b""),
        # The three seq values whose CHECKSUM lands on a framing byte. These are
        # the cases the shipped coex_check gets WRONG today: it does not escape,
        # so at these values it emits a malformed frame.
        ("chk_is_ESC_seq42", DID, CID, 42,   b""),
        ("chk_is_SOP_seq72", DID, CID, 72,   b""),
        ("chk_is_EOP_seq253", DID, CID, 253, b""),
        # Payload bytes that must be escaped.
        ("payload_SOP",      0x1A, 0x0E, 0x05, bytes([0x8D])),
        ("payload_EOP",      0x1A, 0x0E, 0x06, bytes([0xD8])),
        ("payload_ESC",      0x1A, 0x0E, 0x07, bytes([0xAB])),
        ("payload_all_three", 0x1A, 0x0E, 0x08, bytes([0xAB, 0x8D, 0xD8])),
        # Adjacent and repeated escapes -- an encoder that advances its cursor
        # wrongly passes the single-byte cases and fails these.
        ("payload_repeated", 0x1A, 0x0E, 0x09, bytes([0x8D, 0x8D, 0xD8, 0xD8, 0xAB, 0xAB])),
        # A realistic 8-channel LED write, the first real payload command we need.
        ("leds_8ch",         0x1A, 0x1C, 0x0A, bytes([0xFF, 0x00, 0x8D, 0x40,
                                                      0xD8, 0x10, 0xAB, 0x7F])),
        # Every byte value, to make the escape table exhaustive rather than sampled.
        ("payload_0_127",    0x1A, 0x0E, 0x0B, bytes(range(0, 128))),
        ("payload_128_255",  0x1A, 0x0E, 0x0C, bytes(range(128, 256))),
    ]

    print("/* GENERATED by test/gen_fixtures.py from mac-prototype/r2_probe.py.")
    print(" * Do not edit by hand: regenerate so the expectation stays tied to the")
    print(" * implementation it is supposed to match. */")
    print("#pragma once")
    print("#include <stdint.h>\n")
    print("typedef struct {")
    print("    const char    *name;")
    print("    uint8_t        did, cid, seq;")
    print("    const uint8_t *data;   uint32_t data_len;")
    print("    const uint8_t *expect; uint32_t expect_len;")
    print("} r2_vec_t;\n")

    for name, did, cid, seq, data in cases:
        enc = rp.build(did, cid, seq, data)
        print(f"static const uint8_t vec_{name}_in[]  = {c_bytes(data)};")
        print(f"static const uint8_t vec_{name}_out[] = {c_bytes(enc)};")
    print("\nstatic const r2_vec_t R2_VECTORS[] = {")
    for name, did, cid, seq, data in cases:
        print(f"    {{\"{name}\", 0x{did:02X}, 0x{cid:02X}, 0x{seq:02X}, "
              f"vec_{name}_in, {len(data)}, vec_{name}_out, "
              f"sizeof(vec_{name}_out)}},")
    print("};")
    print(f"#define R2_VECTOR_COUNT {len(cases)}\n")

    # Decode vectors: real response frames, including one whose payload needs
    # unescaping. flags 0x09 = IS_RESPONSE | IS_ACTIVITY, as R2 actually replies.
    resp = [
        ("resp_wake_ok",   bytes([0x09, 0x13, 0x0D, 0x02, 0x00])),
        ("resp_with_esc",  bytes([0x09, 0x13, 0x03, 0x13, 0x00, 0x8D, 0xD8, 0xAB])),
        ("resp_err_busy",  bytes([0x09, 0x17, 0x0F, 0x21, 0x08])),
        # HAS_TARGET (0x10) and HAS_SOURCE (0x20) insert bytes BEFORE did/cid/seq.
        # Nothing pinned those skips before; the branches were reasoned from
        # source, which is not the same as tested.
        ("resp_has_target",       bytes([0x19, 0xEE, 0x13, 0x0D, 0x02, 0x00])),
        ("resp_has_source",       bytes([0x29, 0xCC, 0x13, 0x0D, 0x02, 0x00])),
        ("resp_has_both",         bytes([0x39, 0xEE, 0xCC, 0x13, 0x0D, 0x02, 0x00])),
        # A frame with the flags set but NOT a response: no error byte is
        # consumed, so the first data byte must survive.
        ("cmd_shaped_no_err",     bytes([0x0A, 0x1A, 0x1C, 0x33, 0x77, 0x88])),
        # Both extra-id bytes AND an escaped payload, so the skips and the
        # unescaper have to be right at the same time.
        ("resp_both_plus_esc",    bytes([0x39, 0xEE, 0xCC, 0x13, 0x03, 0x14, 0x00, 0xAB, 0x8D])),
    ]
    for name, payload in resp:
        body = payload + bytes((rp.packet_chk(payload),))
        raw = bytes((rp.SOP,)) + rp.escape(body) + bytes((rp.EOP,))
        parsed = rp.parse(raw)
        print(f"static const uint8_t {name}_raw[]  = {c_bytes(raw)};")
        print(f"static const uint8_t {name}_data[] = {c_bytes(parsed.data)};")
    print("\ntypedef struct {")
    print("    const char    *name;")
    print("    const uint8_t *raw;  uint32_t raw_len;")
    print("    uint8_t        flags, did, cid, seq, err;")
    print("    const uint8_t *data; uint32_t data_len;")
    print("} r2_dec_vec_t;\n")
    print("static const r2_dec_vec_t R2_DECODE_VECTORS[] = {")
    for name, payload in resp:
        body = payload + bytes((rp.packet_chk(payload),))
        raw = bytes((rp.SOP,)) + rp.escape(body) + bytes((rp.EOP,))
        p = rp.parse(raw)
        print(f"    {{\"{name}\", {name}_raw, sizeof({name}_raw), "
              f"0x{p.flags:02X}, 0x{p.did:02X}, 0x{p.cid:02X}, 0x{p.seq:02X}, "
              f"0x{p.err:02X}, {name}_data, {len(p.data)}}},")
    print("};")
    print(f"#define R2_DECODE_VECTOR_COUNT {len(resp)}")


if __name__ == "__main__":
    main()
